/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterComplianceReportStatusSummaryReportControlCheck } from './ClusterComplianceReportStatusSummaryReportControlCheck';

/**
 * SummaryReport represents a kubernetes scan report with consolidated findings
 *
 * @export
 */
export interface ClusterComplianceReportStatusSummaryReport {
  /** controlCheck
   *
   * @required {false}
   */
  controlCheck?: ClusterComplianceReportStatusSummaryReportControlCheck[];
  /** id
   *
   * @required {false}
   */
  id?: string;
  /** title
   *
   * @required {false}
   */
  title?: string;
}
