/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterComplianceReportStatusDetailReportResults } from './ClusterComplianceReportStatusDetailReportResults';

/**
 * ComplianceReport represents a kubernetes scan report
 *
 * @export
 */
export interface ClusterComplianceReportStatusDetailReport {
  /** description
   *
   * @required {false}
   */
  description?: string;
  /** id
   *
   * @required {false}
   */
  id?: string;
  /** relatedVersion
   *
   * @required {false}
   */
  relatedVersion?: string[];
  /** results
   *
   * @required {false}
   */
  results?: ClusterComplianceReportStatusDetailReportResults[];
  /** title
   *
   * @required {false}
   */
  title?: string;
  /** version
   *
   * @required {false}
   */
  version?: string;
}
