/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * SpecCheck represent the scanner who perform the control check
 *
 * @export
 */
export interface ClusterComplianceReportSpecComplianceControlsChecks {
  /** id
   * id define the check id as produced by scanner
   *
   * @required {true}
   */
  id: string;
}
