/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface ClusterComplianceReportStatusSummary {
  /** failCount
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  failCount?: number;
  /** passCount
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  passCount?: number;
}
