/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * ComplianceCheck provides the result of conducting a single compliance step.
 *
 * @export
 */
export interface ClusterComplianceReportStatusDetailReportResultsChecks {
  /** category
   *
   * @required {false}
   */
  category?: string;
  /** checkID
   *
   * @required {true}
   */
  checkID: string;
  /** description
   *
   * @required {false}
   */
  description?: string;
  /** messages
   *
   * @required {false}
   */
  messages?: string[];
  /** remediation
   * Remediation provides description or links to external resources to remediate failing check.
   *
   * @required {false}
   */
  remediation?: string;
  /** severity
   * Severity level of a vulnerability or a configuration audit check.
   *
   * @required {true}
   */
  severity: string;
  /** success
   *
   * @required {true}
   */
  success: boolean;
  /** target
   *
   * @required {false}
   */
  target?: string;
  /** title
   *
   * @required {false}
   */
  title?: string;
}
