/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterComplianceReportStatusDetailReportResultsChecks } from './ClusterComplianceReportStatusDetailReportResultsChecks';

export interface ClusterComplianceReportStatusDetailReportResults {
  /** checks
   * ComplianceCheck provides the result of conducting a single compliance step.
   *
   * @required {true}
   */
  checks: ClusterComplianceReportStatusDetailReportResultsChecks[];
  /** description
   *
   * @required {false}
   */
  description?: string;
  /** id
   *
   * @required {false}
   */
  id?: string;
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** severity
   *
   * @required {false}
   */
  severity?: string;
  /** status
   *
   * @required {false}
   */
  status?: string;
}
