/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface ClusterComplianceReportStatusSummaryReportControlCheck {
  /** id
   *
   * @required {false}
   */
  id?: string;
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** severity
   *
   * @required {false}
   */
  severity?: string;
  /** totalFail
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  totalFail?: number;
}
