/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Commands represent the commands to be executed by the node-collector
 *
 * @export
 */
export interface ClusterComplianceReportSpecComplianceControlsCommands {
  /** id
   * id define the commands id
   *
   * @required {true}
   */
  id: string;
}
