/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ConfigAuditReportReportChecks } from './ConfigAuditReportReportChecks';
import { ConfigAuditReportReportScanner } from './ConfigAuditReportReportScanner';
import { ConfigAuditReportReportSummary } from './ConfigAuditReportReportSummary';

export interface ConfigAuditReportReport {
  /** checks
   * Check provides the result of conducting a single audit step.
   *
   * @required {true}
   */
  checks: ConfigAuditReportReportChecks[];
  /** scanner
   * Scanner is the spec for a scanner generating a security assessment report.
   *
   * @required {false}
   */
  scanner?: ConfigAuditReportReportScanner;
  /** summary
   * ConfigAuditSummary counts failed checks by severity.
   *
   * @required {false}
   */
  summary?: ConfigAuditReportReportSummary;
  /** updateTimestamp
   *
   * @required {false}
   * @format {date-time}
   */
  updateTimestamp?: string;
}
