/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Scope indicates the section of config that was audited.
 *
 * @export
 */
export interface ConfigAuditReportReportChecksScope {
  /** type
   * Type indicates type of this scope, e.g. Container, ConfigMapKey or JSONPath.
   *
   * @required {true}
   */
  type: string;
  /** value
   * Value indicates value of this scope that depends on Type, e.g. container name, ConfigMap key or JSONPath expression
   *
   * @required {true}
   */
  value: string;
}
