/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * ConfigAuditSummary counts failed checks by severity.
 *
 * @export
 */
export interface ConfigAuditReportReportSummary {
  /** criticalCount
   * CriticalCount is the number of failed checks with critical severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  criticalCount: number;
  /** highCount
   * HighCount is the number of failed checks with high severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  highCount: number;
  /** lowCount
   * LowCount is the number of failed check with low severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  lowCount: number;
  /** mediumCount
   * MediumCount is the number of failed checks with medium severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  mediumCount: number;
}
