/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * ExposedSecret is the spec for a exposed secret record.
 *
 * @export
 */
export interface ExposedSecretReportReportSecrets {
  /** category
   *
   * @required {true}
   */
  category: string;
  /** match
   * Match where the exposed rule matched.
   *
   * @required {true}
   */
  match: string;
  /** ruleID
   * RuleID is rule the identifier.
   *
   * @required {true}
   */
  ruleID: string;
  /** severity
   * Severity level of a vulnerability or a configuration audit check.
   *
   * @required {true}
   * @originalType {string}
   */
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  /** target
   * Target is where the exposed secret was found.
   *
   * @required {true}
   */
  target: string;
  /** title
   *
   * @required {true}
   */
  title: string;
}
