/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Summary is the exposed secrets counts grouped by Severity.
 *
 * @export
 */
export interface ExposedSecretReportReportSummary {
  /** criticalCount
   * CriticalCount is the number of exposed secrets with Critical Severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  criticalCount: number;
  /** highCount
   * HighCount is the number of exposed secrets with High Severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  highCount: number;
  /** lowCount
   * LowCount is the number of exposed secrets with Low Severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  lowCount: number;
  /** mediumCount
   * MediumCount is the number of exposed secrets with Medium Severity.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  mediumCount: number;
}
