/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Registry is the registry the Artifact was pulled from.
 *
 * @export
 */
export interface ExposedSecretReportReportRegistry {
  /** server
   * Server the FQDN of registry server.
   *
   * @required {false}
   */
  server?: string;
}
