/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { RbacAssessmentReportReportChecks } from './RbacAssessmentReportReportChecks';
import { RbacAssessmentReportReportScanner } from './RbacAssessmentReportReportScanner';
import { RbacAssessmentReportReportSummary } from './RbacAssessmentReportReportSummary';

export interface RbacAssessmentReportReport {
  /** checks
   * Check provides the result of conducting a single audit step.
   *
   * @required {true}
   */
  checks: RbacAssessmentReportReportChecks[];
  /** scanner
   * Scanner is the spec for a scanner generating a security assessment report.
   *
   * @required {true}
   */
  scanner: RbacAssessmentReportReportScanner;
  /** summary
   * RbacAssessmentSummary counts failed checks by severity.
   *
   * @required {true}
   */
  summary: RbacAssessmentReportReportSummary;
}
