/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { SbomReportReportComponentsComponentsHashes } from './SbomReportReportComponentsComponentsHashes';
import { SbomReportReportComponentsComponentsLicenses } from './SbomReportReportComponentsComponentsLicenses';
import { SbomReportReportComponentsComponentsProperties } from './SbomReportReportComponentsComponentsProperties';
import { SbomReportReportComponentsComponentsSupplier } from './SbomReportReportComponentsComponentsSupplier';

export interface SbomReportReportComponentsComponents {
  /** bom-ref
   *
   * @required {false}
   */
  'bom-ref': string;
  /** group
   *
   * @required {false}
   */
  group?: string;
  /** hashes
   *
   * @required {false}
   */
  hashes?: SbomReportReportComponentsComponentsHashes[];
  /** licenses
   *
   * @required {false}
   */
  licenses?: SbomReportReportComponentsComponentsLicenses[];
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** properties
   *
   * @required {false}
   */
  properties?: SbomReportReportComponentsComponentsProperties[];
  /** purl
   *
   * @required {false}
   */
  purl?: string;
  /** supplier
   *
   * @required {false}
   */
  supplier?: SbomReportReportComponentsComponentsSupplier;
  /** type
   *
   * @required {false}
   */
  type?: string;
  /** version
   *
   * @required {false}
   */
  version?: string;
}
