/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface SbomReportReportComponentsDependencies {
  /** dependsOn
   *
   * @required {false}
   */
  dependsOn?: string[];
  /** ref
   *
   * @required {false}
   */
  ref?: string;
}
