/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Summary is a summary of sbom report.
 *
 * @export
 */
export interface SbomReportReportSummary {
  /** componentsCount
   * ComponentsCount is the number of components in bom.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  componentsCount: number;
  /** dependenciesCount
   * DependenciesCount is the number of dependencies in bom.
   *
   * @required {true}
   * @format {int64}
   * @originalType {integer}
   */
  dependenciesCount: number;
}
