/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { SbomReportReportComponentsComponentsLicensesLicense } from './SbomReportReportComponentsComponentsLicensesLicense';

export interface SbomReportReportComponentsComponentsLicenses {
  /** expression
   *
   * @required {false}
   */
  expression?: string;
  /** license
   *
   * @required {false}
   */
  license?: SbomReportReportComponentsComponentsLicensesLicense;
}
