/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface SbomReportReportComponentsComponentsHashes {
  /** alg
   *
   * @required {false}
   */
  alg?: string;
  /** content
   *
   * @required {false}
   */
  content?: string;
}
