/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { SbomReportReportComponentsComponentsSupplierContact } from './SbomReportReportComponentsComponentsSupplierContact';

export interface SbomReportReportComponentsComponentsSupplier {
  /** contact
   *
   * @required {false}
   */
  contact?: SbomReportReportComponentsComponentsSupplierContact[];
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** url
   *
   * @required {false}
   */
  url?: string[];
}
