/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { SbomReportReportArtifact } from './SbomReportReportArtifact';
import { SbomReportReportComponents } from './SbomReportReportComponents';
import { SbomReportReportRegistry } from './SbomReportReportRegistry';
import { SbomReportReportScanner } from './SbomReportReportScanner';
import { SbomReportReportSummary } from './SbomReportReportSummary';

/**
 * Report is the actual sbom report data.
 *
 * @export
 */
export interface SbomReportReport {
  /** artifact
   * Artifact represents a standalone, executable package of software that includes everything needed to
run an application.
   *
   * @required {true}
   */
  artifact: SbomReportReportArtifact;
  /** components
   * Bom is artifact bill of materials.
   *
   * @required {true}
   */
  components: SbomReportReportComponents;
  /** registry
   * Registry is the registry the Artifact was pulled from.
   *
   * @required {false}
   */
  registry?: SbomReportReportRegistry;
  /** scanner
   * Scanner is the scanner that generated this report.
   *
   * @required {true}
   */
  scanner: SbomReportReportScanner;
  /** summary
   * Summary is a summary of sbom report.
   *
   * @required {true}
   */
  summary: SbomReportReportSummary;
  /** updateTimestamp
   * UpdateTimestamp is a timestamp representing the server time in UTC when this report was updated.
   *
   * @required {true}
   * @format {date-time}
   */
  updateTimestamp: string;
}
