/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { SbomReportReportComponentsComponents } from './SbomReportReportComponentsComponents';
import { SbomReportReportComponentsDependencies } from './SbomReportReportComponentsDependencies';
import { SbomReportReportComponentsMetadata } from './SbomReportReportComponentsMetadata';

/**
 * Bom is artifact bill of materials.
 *
 * @export
 */
export interface SbomReportReportComponents {
  /** bomFormat
   *
   * @required {true}
   */
  bomFormat: string;
  /** components
   *
   * @required {false}
   */
  components?: SbomReportReportComponentsComponents[];
  /** dependencies
   *
   * @required {false}
   */
  dependencies?: SbomReportReportComponentsDependencies[];
  /** metadata
   *
   * @required {false}
   */
  metadata?: SbomReportReportComponentsMetadata;
  /** serialNumber
   *
   * @required {false}
   */
  serialNumber?: string;
  /** specVersion
   *
   * @required {true}
   */
  specVersion: string;
  /** version
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  version?: number;
}
