/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface SbomReportReportComponentsComponentsProperties {
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** value
   *
   * @required {false}
   */
  value?: string;
}
